[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "setting_src20_attributes"

[dependencies]
src20 = "0.8.0"
asset = { path = "../../../libs/asset" }
