[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "admin_examples"

[dependencies]
admin = { path = "../../libs/admin" }
ownership = { path = "../../libs/ownership" }
