[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "pausable_with_ownership_example"

[dependencies]
pausable = { path = "../../../libs/pausable" }
ownership = { path = "../../../libs/ownership" }
