[workspace]
members = [
  "./admin",

  "./bytecode",
  "./merkle_binary",
  "./merkle_sparse",
  "./ownership",
  "./ownership_configurable",
  "./pausable/pausable",
  "./pausable/pausable_with_ownership",
  "./queue",
  "./reentrancy",
  "./signed_integers",
  "./big_integers",
  "./upgradability",
  "./hash_map",
]
