[workspace]
members = [
  "./admin",
  "./asset/base_docs",
  "./asset/basic_src3",
  "./asset/basic_src7",
  "./asset/basic_src20",
  "./asset/metadata_docs",
  "./asset/setting_src7_attributes",
  "./asset/setting_src20_attributes",
  "./asset/supply_docs",
  "./bytecode",
  "./fixed_point",
  "./merkle",
  "./ownership",
  "./pausable/pausable",
  "./pausable/pausable_with_ownership",
  "./queue",
  "./reentrancy",
  "./signed_integers",
]
