name: Docs

on:
  pull_request:

jobs:
  spell-check:
    name: Spell Check
    uses: FuelLabs/github-actions/.github/workflows/mdbook-docs.yml@master
    with:
      docs-src-path: "docs/book/src"
      spellcheck-config-path: "docs/book/.spellcheck.yml"

  link-check:
    name: Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
        with:
          configuration-path: ".markdown-link-check.json"

  lint-docs:
    name: Lint Docs
    runs-on: ubuntu-latest
    needs: link-check
    steps:
      - uses: actions/checkout@v3
      - uses: FuelLabs/github-actions/setups/node@master
        with:
          node-version: '16'
          pnpm: true
      - name: Install Dependencies
        run: pnpm install
      - name: Lint Check
        run: pnpm lint:check
