name: Docs

on:
  pull_request:

jobs:
  spell-check:
    name: Spell Check
    uses: FuelLabs/github-actions/.github/workflows/mdbook-docs.yml@master
    with:
      docs-src-path: "docs/book/src"
      spellcheck-config-path: "docs/book/.spellcheck.yml"

  link-check:
    name: Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
        with:
          configuration-path: "docs/book/.markdown-link-check.json"

  lint-docs:
    name: Lint Docs
    runs-on: ubuntu-latest
    needs: link-check
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install Markdown Linter
        run: pip install pymarkdownlint
      - name: Lint Markdown Files
        run: pymarkdownlint docs/book

