name: Docs

on:
  pull_request:
    paths:
      - docs/**

jobs:
  spell-check:
    name: Spell Check
    uses: FuelLabs/github-actions/.github/workflows/mdbook-docs.yml@master
    with:
      docs-src-path: "docs/book/src"
      spellcheck-config-path: "docs/book/.spellcheck.yml"

  lint-docs:
    name: Lint Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FuelLabs/github-actions/setups/node@master
      - name: Lint Check
        run: |
          pnpm install
          pnpm lint:check

  check-links:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install -g linkinator

      - name: Check Links
        run: |
          linkinator "docs/book/src" --silent
