name: Docs

on:
  pull_request:

jobs:
  spell-check:
    name: Spell Check
    uses: FuelLabs/github-actions/.github/workflows/mdbook-docs.yml@master
    with:
      docs-src-path: "docs/book/src"
      spellcheck-config-path: "docs/book/.spellcheck.yml"

  link-check:
    name: Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.9.0
        with:
          args: >-
            --no-progress
            --exclude-mail
            --exclude "http://127.0.0.1*"
            --exclude "https://127.0.0.1*"
            --exclude "http://localhost*"
            --accept 200,206,301,302,304,403,405,429
            --max-concurrency 4
            --timeout 20
            "docs/book/src/**/*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
